/**
 * Applications Page Mock Data
 * 
 * This file contains mock data for the applications queue and application details.
 * Import from here instead of defining in page components.
 */

import type { Application } from "@/types/compliance";

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "APP-2024-001",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 65,
    riskBand: "MEDIUM",
    assignedOfficer: "Jane Mensah",
    submittedAt: "2026-06-02T14:30:00Z",
    slaDeadline: "2026-06-04T14:30:00Z",
    screeningStatus: "PENDING",
    applicant: {
      legalName: "Kwame Tech Solutions Ltd",
      phone: "+233244123456",
      email: "info@kwametech.com",
      registrationNumber: "CS-123456",
      industry: "E-commerce",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-101",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 65,
    riskBand: "MEDIUM",
    assignedOfficer: "Jane Mensah",
    submittedAt: "2026-06-02T14:30:00Z",
    slaDeadline: "2026-06-04T14:30:00Z",
    screeningStatus: "PENDING",
    applicant: {
      legalName: "Kwame Tech Solutions Ltd",
      phone: "+233244123456",
      email: "info@kwametech.com",
      registrationNumber: "CS-123456",
      industry: "E-commerce",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-201",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 65,
    riskBand: "MEDIUM",
    assignedOfficer: "Jane Mensah",
    submittedAt: "2026-06-02T14:30:00Z",
    slaDeadline: "2026-06-04T14:30:00Z",
    screeningStatus: "PENDING",
    applicant: {
      legalName: "Kwame Tech Solutions Ltd",
      phone: "+233244123456",
      email: "info@kwametech.com",
      registrationNumber: "CS-123456",
      industry: "E-commerce",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-002",
    type: "INDIVIDUAL",
    status: "PENDING_INFO",
    riskScore: 25,
    riskBand: "LOW",
    assignedOfficer: "John Mensah",
    submittedAt: "2026-06-01T09:15:00Z",
    slaDeadline: "2026-06-05T09:15:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      fullName: "Sarah Osei",
      phone: "+233244987654",
      email: "sarah.osei@gmail.com",
      occupation: "Freelance Designer",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-003",
    type: "BUSINESS",
    status: "ESCALATED",
    riskScore: 85,
    riskBand: "HIGH",
    assignedOfficer: "Jane Mensah",
    submittedAt: "2026-05-30T11:45:00Z",
    slaDeadline: "2026-06-03T11:45:00Z",
    screeningStatus: "HIT",
    applicant: {
      legalName: "Global Traders Ltd",
      phone: "+233201234567",
      email: "contact@globaltraders.gh",
      registrationNumber: "CS-789012",
      industry: "Import/Export",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-004",
    type: "INDIVIDUAL",
    status: "SUBMITTED",
    riskScore: 45,
    riskBand: "MEDIUM",
    submittedAt: "2026-06-03T16:20:00Z",
    slaDeadline: "2026-06-05T16:20:00Z",
    screeningStatus: "PENDING",
    applicant: {
      fullName: "Kwaku Mensah",
      phone: "+233244555666",
      email: "kwaku.m@yahoo.com",
      occupation: "Business Owner",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-005",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-00232",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-0092",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-0062",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-0022",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
  {
    id: "APP-2024-0042",
    type: "BUSINESS",
    status: "UNDER_REVIEW",
    riskScore: 35,
    riskBand: "LOW",
    assignedOfficer: "Peter Owusu",
    submittedAt: "2026-06-02T10:00:00Z",
    slaDeadline: "2026-06-04T10:00:00Z",
    screeningStatus: "CLEAR",
    applicant: {
      legalName: "Bright Future Schools",
      phone: "+233302123456",
      email: "admin@brightfuture.edu.gh",
      registrationNumber: "CS-345678",
      industry: "Education",
    },
    documents: [],
    screeningResults: [],
    notes: [],
    auditTrail: [],
  },
];

// Mock data for application detail view
export const MOCK_APPLICATION_DETAIL = {
  id: "APP-2024-001",
  type: "BUSINESS" as const,
  status: "UNDER_REVIEW" as const,
  riskScore: 65,
  riskBand: "MEDIUM" as const,
  assignedOfficer: "Jane Mensah",
  submittedAt: "2026-06-02T14:30:00Z",
  slaDeadline: "2026-06-04T14:30:00Z",
  screeningStatus: "PENDING" as const,
  applicant: {
    legalName: "Kwame Tech Solutions Ltd",
    tradingName: "KTS Digital",
    businessType: "Limited Liability Company",
    registrationNumber: "CS-123456",
    dateOfIncorporation: "2020-05-15",
    registeredAddress: "123 Independence Ave, Accra, Ghana",
    operatingAddress: "123 Independence Ave, Accra, Ghana",
    industry: "E-commerce Technology",
    website: "https://www.kwametech.com",
    phone: "+233244123456",
    email: "info@kwametech.com",
    tin: "C0012345678",
    expectedMonthlyVolume: 150000,
    intendedChannels: ["Mobile Money", "Bank Transfer", "Card Payments"],
  },
  documents: [
    {
      id: "DOC-001",
      type: "BUSINESS_REG",
      status: "VERIFIED" as "VERIFIED" | "PENDING" | "REJECTED" | "EXPIRED",
      uploadedAt: "2026-06-02T14:35:00Z",
      fileName: "business_registration.pdf",
      fileSize: 245678,
    },
    {
      id: "DOC-002",
      type: "TAX_CERT",
      status: "PENDING" as "VERIFIED" | "PENDING" | "REJECTED" | "EXPIRED",
      uploadedAt: "2026-06-02T14:36:00Z",
      fileName: "tax_certificate.pdf",
      fileSize: 189234,
    },
    {
      id: "DOC-003",
      type: "DIRECTORS_ID",
      status: "PENDING" as "VERIFIED" | "PENDING" | "REJECTED" | "EXPIRED",
      uploadedAt: "2026-06-02T14:38:00Z",
      fileName: "director_id.pdf",
      fileSize: 567890,
    },
  ],
  beneficialOwners: [
    {
      id: "BO-001",
      name: "Kwame Mensah",
      dateOfBirth: "1985-03-20",
      nationality: "Ghanaian",
      ownershipPercent: 60,
      role: "DIRECTOR" as const,
      screeningStatus: "CLEAR" as const,
    },
    {
      id: "BO-002",
      name: "Abena Osei",
      dateOfBirth: "1988-07-12",
      nationality: "Ghanaian",
      ownershipPercent: 40,
      role: "SHAREHOLDER" as const,
      screeningStatus: "PENDING" as const,
    },
  ],
  notes: [
    {
      id: "NOTE-001",
      content: "Initial review completed. Tax certificate needs verification.",
      author: "CO-001",
      authorName: "Jane Mensah",
      createdAt: "2026-06-03T09:15:00Z",
      isInternal: true,
    },
  ],
  auditTrail: [
    {
      id: "AUDIT-001",
      actor: "CO-001",
      actorName: "Jane Mensah",
      action: "Application submitted",
      targetType: "APPLICATION",
      targetId: "APP-2024-001",
      timestamp: "2026-06-02T14:30:00Z",
    },
    {
      id: "AUDIT-002",
      actor: "CO-001",
      actorName: "Jane Mensah",
      action: "Assigned to officer",
      targetType: "APPLICATION",
      targetId: "APP-2024-001",
      timestamp: "2026-06-03T09:00:00Z",
    },
  ],
};
