/**
 * Cases Page Mock Data
 * 
 * This file contains mock data for case management and investigations.
 */

import { Case } from "@/types/compliance";

export const MOCK_CASES: Case[] = [
  {
    id: "CASE-2024-001",
    type: "SANCTIONS_HIT",
    priority: "CRITICAL",
    status: "INVESTIGATING",
    linkedEntities: ["APP-2024-003", "MERCH-002"],
    assignedInvestigator: "Jane Mensah",
    openedAt: "2024-02-20T09:00:00Z",
    openedBy: "System",
    evidence: [],
    notes: [],
    tasks: [
      {
        id: "TASK-001",
        description: "Review sanctions match details",
        assignedTo: "Jane Mensah",
        dueDate: "2024-02-21T17:00:00Z",
        completed: true,
        completedAt: "2024-02-20T14:30:00Z",
      },
      {
        id: "TASK-002",
        description: "Interview applicant",
        assignedTo: "Jane Mensah",
        dueDate: "2024-02-22T17:00:00Z",
        completed: false,
      },
    ],
  },
  {
    id: "CASE-2024-002",
    type: "SUSPICIOUS_ACTIVITY",
    priority: "HIGH",
    status: "OPEN",
    linkedEntities: ["MERCH-005"],
    assignedInvestigator: "Kwame Asante",
    openedAt: "2024-02-19T11:30:00Z",
    openedBy: "Jane Mensah",
    evidence: [],
    notes: [],
    tasks: [],
  },
  {
    id: "CASE-2024-003",
    type: "DOCUMENT_FRAUD",
    priority: "HIGH",
    status: "PENDING_REVIEW",
    linkedEntities: ["APP-2024-007"],
    assignedInvestigator: "Jane Mensah",
    openedAt: "2024-02-18T15:20:00Z",
    openedBy: "Kwame Asante",
    evidence: [],
    notes: [],
    tasks: [],
  },
  {
    id: "CASE-2024-004",
    type: "COMPLAINT",
    priority: "MEDIUM",
    status: "CLOSED",
    linkedEntities: ["MERCH-003"],
    assignedInvestigator: "Kwame Asante",
    openedAt: "2024-02-15T10:00:00Z",
    openedBy: "System",
    closedAt: "2024-02-19T16:45:00Z",
    outcome: "Complaint resolved - customer service issue addressed",
    evidence: [],
    notes: [],
    tasks: [],
  },
  {
    id: "CASE-2024-005",
    type: "SUSPICIOUS_ACTIVITY",
    priority: "CRITICAL",
    status: "REPORTED",
    linkedEntities: ["MERCH-001", "MERCH-008"],
    assignedInvestigator: "Jane Mensah",
    openedAt: "2024-02-10T08:30:00Z",
    openedBy: "Jane Mensah",
    closedAt: "2024-02-17T14:20:00Z",
    outcome: "Suspicious Transaction Report filed with FIU",
    evidence: [],
    notes: [],
    tasks: [],
    strDraft: "STR filed - Case #STR-2024-005",
  },
];

// Mock data for case detail view
export const getCaseDetailData = (id: string): Case => ({
  id,
  type: "SANCTIONS_HIT",
  priority: "CRITICAL",
  status: "INVESTIGATING",
  linkedEntities: ["APP-2024-003", "MERCH-002"],
  assignedInvestigator: "Jane Mensah",
  openedAt: "2024-02-20T09:00:00Z",
  openedBy: "System",
  evidence: [
    {
      id: "EV-001",
      type: "DOCUMENT",
      description: "Sanctions screening report showing 85% match",
      fileUrl: "#",
      addedBy: "Jane Mensah",
      addedAt: "2024-02-20T10:30:00Z",
    },
    {
      id: "EV-002",
      type: "SCREENSHOT",
      description: "Screenshot of OFAC list entry",
      fileUrl: "#",
      addedBy: "Jane Mensah",
      addedAt: "2024-02-20T11:15:00Z",
    },
    {
      id: "EV-003",
      type: "NOTE",
      description: "Initial assessment notes from screening review",
      addedBy: "Jane Mensah",
      addedAt: "2024-02-20T09:30:00Z",
    },
  ],
  notes: [
    {
      id: "NOTE-001",
      content: "Initial screening triggered on name match. Subject name matches OFAC list entry with 85% confidence. Proceeding with detailed investigation.",
      author: "jane.mensah@namibrapay.com",
      authorName: "Jane Mensah",
      createdAt: "2024-02-20T09:30:00Z",
      isInternal: true,
    },
    {
      id: "NOTE-002",
      content: "Reviewed additional identifiers. Date of birth differs by 2 years. Nationality matches. Need to verify with government database.",
      author: "jane.mensah@namibrapay.com",
      authorName: "Jane Mensah",
      createdAt: "2024-02-20T14:20:00Z",
      isInternal: true,
    },
    {
      id: "NOTE-003",
      content: "Contacted applicant for additional documentation. Awaiting response.",
      author: "jane.mensah@namibrapay.com",
      authorName: "Jane Mensah",
      createdAt: "2024-02-21T10:00:00Z",
      isInternal: false,
    },
  ],
  tasks: [
    {
      id: "TASK-001",
      description: "Review sanctions match details and compare all identifiers",
      assignedTo: "Jane Mensah",
      dueDate: "2024-02-21T17:00:00Z",
      completed: true,
      completedAt: "2024-02-20T14:30:00Z",
    },
    {
      id: "TASK-002",
      description: "Request additional identity documents from applicant",
      assignedTo: "Jane Mensah",
      dueDate: "2024-02-22T17:00:00Z",
      completed: true,
      completedAt: "2024-02-21T10:05:00Z",
    },
    {
      id: "TASK-003",
      description: "Verify identity with government database",
      assignedTo: "Jane Mensah",
      dueDate: "2024-02-23T17:00:00Z",
      completed: false,
    },
    {
      id: "TASK-004",
      description: "Prepare case summary for senior review",
      assignedTo: "Jane Mensah",
      dueDate: "2024-02-24T17:00:00Z",
      completed: false,
    },
  ],
  strDraft: "",
});
