import type { SelectOption } from "@/components/ui/select.tsx";

// ── Country Options ──────────────────────────────────────────────

export const COUNTRY_OPTIONS: SelectOption[] = [
  // African Countries (Priority)
  { value: "GH", label: "Ghana" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "ZA", label: "South Africa" },
  { value: "TZ", label: "Tanzania" },
  { value: "UG", label: "Uganda" },
  { value: "RW", label: "Rwanda" },
  { value: "ET", label: "Ethiopia" },
  { value: "EG", label: "Egypt" },
  { value: "MA", label: "Morocco" },
  { value: "DZ", label: "Algeria" },
  { value: "TN", label: "Tunisia" },
  { value: "SN", label: "Senegal" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "CM", label: "Cameroon" },
  { value: "AO", label: "Angola" },
  { value: "MZ", label: "Mozambique" },
  { value: "BW", label: "Botswana" },
  { value: "NA", label: "Namibia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "ZM", label: "Zambia" },
  { value: "MW", label: "Malawi" },
  { value: "MG", label: "Madagascar" },
  { value: "MU", label: "Mauritius" },
  { value: "BJ", label: "Benin" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cape Verde" },
  { value: "TD", label: "Chad" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "DR Congo" },
  { value: "DJ", label: "Djibouti" },
  { value: "ER", label: "Eritrea" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "ML", label: "Mali" },
  { value: "MR", label: "Mauritania" },
  { value: "NE", label: "Niger" },
  { value: "SO", label: "Somalia" },
  { value: "SS", label: "South Sudan" },
  { value: "SD", label: "Sudan" },
  { value: "TG", label: "Togo" },
  { value: "SL", label: "Sierra Leone" },
  
  // Other Major Markets
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "IN", label: "India" },
  { value: "CN", label: "China" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "SG", label: "Singapore" },
  { value: "MY", label: "Malaysia" },
  { value: "ID", label: "Indonesia" },
  { value: "PH", label: "Philippines" },
  { value: "TH", label: "Thailand" },
  { value: "VN", label: "Vietnam" },
  { value: "PK", label: "Pakistan" },
  { value: "BD", label: "Bangladesh" },
  { value: "LK", label: "Sri Lanka" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "QA", label: "Qatar" },
  { value: "KW", label: "Kuwait" },
  { value: "BH", label: "Bahrain" },
  { value: "OM", label: "Oman" },
  { value: "JO", label: "Jordan" },
  { value: "LB", label: "Lebanon" },
  { value: "IL", label: "Israel" },
  { value: "TR", label: "Turkey" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "YE", label: "Yemen" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "PE", label: "Peru" },
  { value: "VE", label: "Venezuela" },
  { value: "EC", label: "Ecuador" },
  { value: "BO", label: "Bolivia" },
  
  // Europe
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "PT", label: "Portugal" },
  { value: "NL", label: "Netherlands" },
  { value: "BE", label: "Belgium" },
  { value: "CH", label: "Switzerland" },
  { value: "AT", label: "Austria" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "IE", label: "Ireland" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "RO", label: "Romania" },
  { value: "GR", label: "Greece" },
  { value: "HR", label: "Croatia" },
  { value: "UA", label: "Ukraine" },
  { value: "RU", label: "Russia" },
  
  // Other
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
];

// ── Industry Options ─────────────────────────────────────────────

export const INDUSTRY_OPTIONS: SelectOption[] = [
  { value: "ecommerce", label: "E-commerce & Online Retail" },
  { value: "fintech", label: "Financial Technology" },
  { value: "education", label: "Education & E-learning" },
  { value: "healthcare", label: "Healthcare & Wellness" },
  { value: "logistics", label: "Logistics & Delivery" },
  { value: "hospitality", label: "Hospitality & Travel" },
  { value: "entertainment", label: "Entertainment & Media" },
  { value: "nonprofit", label: "Non-profit & NGO" },
  { value: "professional_services", label: "Professional Services" },
  { value: "retail", label: "Retail & Point of Sale" },
  { value: "utilities", label: "Utilities & Bill Payments" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "agriculture", label: "Agriculture & Agribusiness" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "real_estate", label: "Real Estate" },
  { value: "construction", label: "Construction" },
  { value: "automotive", label: "Automotive" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "other", label: "Other" },
];

// ── Bank Options (Ghana) ─────────────────────────────────────────

export const BANK_OPTIONS_GHANA: SelectOption[] = [
  { value: "UMB", label: "Universal Merchant Bank (UMB)" },
  { value: "GCB", label: "GCB Bank" },
  { value: "Ecobank", label: "Ecobank Ghana" },
  { value: "Absa", label: "Absa Bank Ghana" },
  { value: "Stanbic", label: "Stanbic Bank Ghana" },
  { value: "Zenith", label: "Zenith Bank Ghana" },
  { value: "Fidelity", label: "Fidelity Bank Ghana" },
  { value: "Guaranty Trust", label: "Guaranty Trust Bank Ghana" },
  { value: "Standard Chartered", label: "Standard Chartered Bank Ghana" },
  { value: "Consolidated Bank", label: "Consolidated Bank Ghana" },
  { value: "Agricultural Development Bank", label: "Agricultural Development Bank" },
  { value: "National Investment Bank", label: "National Investment Bank" },
  { value: "CalBank", label: "CalBank" },
  { value: "Access Bank", label: "Access Bank Ghana" },
  { value: "First National Bank", label: "First National Bank Ghana" },
  { value: "Prudential Bank", label: "Prudential Bank" },
  { value: "Société Générale", label: "Société Générale Ghana" },
  { value: "Republic Bank", label: "Republic Bank Ghana" },
  { value: "Bank of Africa", label: "Bank of Africa Ghana" },
  { value: "FirstBank", label: "First Bank of Nigeria (Ghana)" },
];

// ── Business Type Options ────────────────────────────────────────

export const BUSINESS_TYPE_OPTIONS: SelectOption[] = [
  { value: "starter", label: "Starter Business" },
  { value: "registered", label: "Registered Business" },
];

// ── Developer Options ────────────────────────────────────────────

export const DEVELOPER_OPTIONS: SelectOption[] = [
  { value: "yes", label: "Yes, I am" },
  { value: "no", label: "No, I'm not" },
];

// ── Phone Code Options ───────────────────────────────────────────

export const PHONE_CODE_OPTIONS: SelectOption[] = [
  // African Countries (Priority)
  { value: "+233", label: "+233 (Ghana)" },
  { value: "+234", label: "+234 (Nigeria)" },
  { value: "+254", label: "+254 (Kenya)" },
  { value: "+27", label: "+27 (South Africa)" },
  { value: "+255", label: "+255 (Tanzania)" },
  { value: "+256", label: "+256 (Uganda)" },
  { value: "+250", label: "+250 (Rwanda)" },
  { value: "+251", label: "+251 (Ethiopia)" },
  { value: "+20", label: "+20 (Egypt)" },
  { value: "+212", label: "+212 (Morocco)" },
  { value: "+213", label: "+213 (Algeria)" },
  { value: "+216", label: "+216 (Tunisia)" },
  { value: "+221", label: "+221 (Senegal)" },
  { value: "+225", label: "+225 (Côte d'Ivoire)" },
  { value: "+237", label: "+237 (Cameroon)" },
  { value: "+244", label: "+244 (Angola)" },
  { value: "+258", label: "+258 (Mozambique)" },
  { value: "+267", label: "+267 (Botswana)" },
  { value: "+264", label: "+264 (Namibia)" },
  { value: "+263", label: "+263 (Zimbabwe)" },
  { value: "+260", label: "+260 (Zambia)" },
  { value: "+265", label: "+265 (Malawi)" },
  { value: "+261", label: "+261 (Madagascar)" },
  { value: "+230", label: "+230 (Mauritius)" },
  { value: "+229", label: "+229 (Benin)" },
  { value: "+226", label: "+226 (Burkina Faso)" },
  { value: "+257", label: "+257 (Burundi)" },
  { value: "+238", label: "+238 (Cape Verde)" },
  { value: "+235", label: "+235 (Chad)" },
  { value: "+242", label: "+242 (Congo)" },
  { value: "+243", label: "+243 (DR Congo)" },
  { value: "+253", label: "+253 (Djibouti)" },
  { value: "+291", label: "+291 (Eritrea)" },
  { value: "+241", label: "+241 (Gabon)" },
  { value: "+220", label: "+220 (Gambia)" },
  { value: "+224", label: "+224 (Guinea)" },
  { value: "+245", label: "+245 (Guinea-Bissau)" },
  { value: "+266", label: "+266 (Lesotho)" },
  { value: "+231", label: "+231 (Liberia)" },
  { value: "+218", label: "+218 (Libya)" },
  { value: "+223", label: "+223 (Mali)" },
  { value: "+222", label: "+222 (Mauritania)" },
  { value: "+227", label: "+227 (Niger)" },
  { value: "+252", label: "+252 (Somalia)" },
  { value: "+211", label: "+211 (South Sudan)" },
  { value: "+249", label: "+249 (Sudan)" },
  { value: "+228", label: "+228 (Togo)" },
  { value: "+232", label: "+232 (Sierra Leone)" },
  
  // North America
  { value: "+1", label: "+1 (United States/Canada)" },
  
  // Europe
  { value: "+44", label: "+44 (United Kingdom)" },
  { value: "+49", label: "+49 (Germany)" },
  { value: "+33", label: "+33 (France)" },
  { value: "+39", label: "+39 (Italy)" },
  { value: "+34", label: "+34 (Spain)" },
  { value: "+351", label: "+351 (Portugal)" },
  { value: "+31", label: "+31 (Netherlands)" },
  { value: "+32", label: "+32 (Belgium)" },
  { value: "+41", label: "+41 (Switzerland)" },
  { value: "+43", label: "+43 (Austria)" },
  { value: "+46", label: "+46 (Sweden)" },
  { value: "+47", label: "+47 (Norway)" },
  { value: "+45", label: "+45 (Denmark)" },
  { value: "+358", label: "+358 (Finland)" },
  { value: "+353", label: "+353 (Ireland)" },
  { value: "+48", label: "+48 (Poland)" },
  { value: "+420", label: "+420 (Czech Republic)" },
  { value: "+40", label: "+40 (Romania)" },
  { value: "+30", label: "+30 (Greece)" },
  { value: "+385", label: "+385 (Croatia)" },
  { value: "+380", label: "+380 (Ukraine)" },
  { value: "+7", label: "+7 (Russia)" },
  
  // Asia
  { value: "+91", label: "+91 (India)" },
  { value: "+86", label: "+86 (China)" },
  { value: "+81", label: "+81 (Japan)" },
  { value: "+82", label: "+82 (South Korea)" },
  { value: "+65", label: "+65 (Singapore)" },
  { value: "+60", label: "+60 (Malaysia)" },
  { value: "+62", label: "+62 (Indonesia)" },
  { value: "+63", label: "+63 (Philippines)" },
  { value: "+66", label: "+66 (Thailand)" },
  { value: "+84", label: "+84 (Vietnam)" },
  { value: "+92", label: "+92 (Pakistan)" },
  { value: "+880", label: "+880 (Bangladesh)" },
  { value: "+94", label: "+94 (Sri Lanka)" },
  
  // Middle East
  { value: "+971", label: "+971 (United Arab Emirates)" },
  { value: "+966", label: "+966 (Saudi Arabia)" },
  { value: "+974", label: "+974 (Qatar)" },
  { value: "+965", label: "+965 (Kuwait)" },
  { value: "+973", label: "+973 (Bahrain)" },
  { value: "+968", label: "+968 (Oman)" },
  { value: "+962", label: "+962 (Jordan)" },
  { value: "+961", label: "+961 (Lebanon)" },
  { value: "+972", label: "+972 (Israel)" },
  { value: "+90", label: "+90 (Turkey)" },
  { value: "+98", label: "+98 (Iran)" },
  { value: "+964", label: "+964 (Iraq)" },
  { value: "+967", label: "+967 (Yemen)" },
  
  // Oceania
  { value: "+61", label: "+61 (Australia)" },
  { value: "+64", label: "+64 (New Zealand)" },
  
  // Latin America
  { value: "+55", label: "+55 (Brazil)" },
  { value: "+52", label: "+52 (Mexico)" },
  { value: "+54", label: "+54 (Argentina)" },
  { value: "+56", label: "+56 (Chile)" },
  { value: "+57", label: "+57 (Colombia)" },
  { value: "+51", label: "+51 (Peru)" },
  { value: "+58", label: "+58 (Venezuela)" },
  { value: "+593", label: "+593 (Ecuador)" },
  { value: "+591", label: "+591 (Bolivia)" },
  
  // Other
  { value: "+93", label: "+93 (Afghanistan)" },
  { value: "+355", label: "+355 (Albania)" },
];
